### ISSUE TITLE
ErrCheck is slow

### ISSUE THREAD

**Issue by oryband** [kisielk/errcheck#56] opened 2015-01-19 12:10 UTC
Why does it take 2 seconds for ErrCheck to run on a small codebase? I wish it could be fast, so I could integrate it with Vim/Syntastic (See scrooloose/syntastic#1286) and run the check on every file save `:w`.

**Comment by kisielk** [comment] 2015-01-19 16:54
Most of the time is spent parsing and loading files, something that's out of our control. Future versions of go/loader will have parallel loading so that should speed things up on a per-package basis.

We could also make errcheck run concurrently when multiple packages are passed as arguments.

**Comment by zimmski** [comment] 2015-01-19 17:14
@oryband: Could you try https://github.com/kisielk/errcheck/pull/57 with your 2s use-case.

The problem is indeed go/loader but also the way errcheck works. It needs to load every involved package so it can determine the API of calls. I am looking at this from time to time because of #45 but I do not see an easy solution.

**Comment by kisielk** [comment] 2015-01-29 16:25
We integrated concurrent package checking last week. Can you try the latest version and see if it's fast enough for you?

**Comment by alecthomas** [comment] 2015-02-08 22:46
Anecdotally, comparing github.com/Sean-Der/errcheck and github.com/kisielk/errcheck on the same codebase, the former typically takes about 0.5 seconds and the latter takes around 2.4 seconds.

**Comment by zimmski** [comment] 2015-02-08 22:50
@alecthomas: Can you test with your use case if this is the commit https://github.com/kisielk/errcheck/commit/0ba3e8228e4772238bee75d33c4cb0c3fb2a432c which made things slow for you?

**Comment by alecthomas** [comment] 2015-02-08 23:14
I'm assuming it is that commit, as that was the purpose of Sen-Der's fork, but I can't check. I tried both reverting that commit and rolling back to the prior commit. The former resulted in many merge conflicts and the latter failed (seemingly) due to changes in go/types.

**Comment by alecthomas** [comment] 2015-04-14 01:06
More detail. It appears that if you use `./...` then this repo is fastest, so there is some constant up-front cost but after that is very fast. With the Sean-Der fork, individual directories are fast but total time with checking recursively is much slower (2.9s vs. 5.7s).

**Comment by kisielk** [comment] 2015-04-14 01:08
There's been quite a few updates since the last comment that would likely
have improved the speed as well.

**Comment by oryband** [comment] 2015-04-14 07:53
Hey all. I can confirm it's a lot faster now. Thanks! Next goal: Making it run automatically on every buffer save in vim, just like govet and golint. :)

**Comment by kisielk** [comment] 2015-04-14 07:57
I'm going to close this issue now, I did some profiling on a few runs and nearly all the time is taken up in go/loader especially for smaller checks. Fortunately it does some caching of imports so running it on larger sets of packages eliminates the overhead. I don't think we're going to move away from go/loader at this point, and so any performance improvements that will happen are entirely dependent on that package. It looks like they still have some optimizations they can do since the source code has some comments about caching calls to build.Import as it does some redundant imports at the moment. I don't feel there's anything more actionable here for us though, unless someone feels like writing some patches for go/loader :)

**Closed by kisielk** 2015-04-14 07:57 UTC

**Comment by alecthomas** [comment] 2015-05-08 03:58
Further to what @kisielk described, it seems a large amount of time in go/loader is consumed by `processCgoFiles()`...

**Comment by oryband** [comment] 2015-05-08 14:09
any chance to report these issues upstream to go/loader guys?

**Comment by alecthomas** [comment] 2015-05-11 23:41
@oryband I just use [this fork](https://github.com/Sean-Der/errcheck). It's about 2x-5x faster for the common case, and there don't seem to be any functional differences (it reports the same errors).

As an aside, it's ironic that the commit message on [the change](https://github.com/kisielk/errcheck/commit/0ba3e8228e4772238bee75d33c4cb0c3fb2a432c) that introduced the performance issue is prefixed with "optimization" :)
