### ISSUE TITLE
error return value not checked, but errcheck is no found.

### ISSUE THREAD

**Issue by runner-mei** [kisielk/errcheck#127] opened 2017-09-08 11:50 UTC
code as follow:
````go
package main

import "os"

func aa() error {
	out, err := os.Create("aa")
	if err != nil {
		return err
	}

	err = out.Close()
	return nil
}

````

run errcheck is nothing in then console.

error return value not checked
````go
err = out.Close()
````

**Comment by shurcooL** [comment] 2017-09-08 14:03
Looks similar to #125. /cc @dominikh

**Comment by dominikh** [comment] 2017-09-08 14:06
Yeah, that's a duplicate of #125, which itself is a duplicate of #7 (of sorts)

**Closed by dominikh** 2017-09-08 14:06 UTC
